# Generated by Django 4.0.1 on 2023-08-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_alter_category_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_salt',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
    ]
